# Kribble Mobile Testing Tunnel Script
# This script automates exposing your local development server to the internet
# for testing on mobile devices

param(
    [Parameter()]
    [ValidateSet("ngrok", "cloudflare", "localtunnel")]
    [string]$Provider = "ngrok",
    
    [Parameter()]
    [int]$BackendPort = 3001,
    
    [Parameter()]
    [int]$FrontendPort = 5173,
    
    [Parameter()]
    [switch]$StaticDomain,
    
    [Parameter()]
    [string]$Domain = ""
)

$ErrorActionPreference = "Stop"

# Colors for output
$Green = "`e[32m"
$Yellow = "`e[33m"
$Red = "`e[31m"
$Cyan = "`e[36m"
$Reset = "`e[0m"

function Write-Status($message) {
    Write-Host "${Cyan}[KRIBBLE]${Reset} $message"
}

function Write-Success($message) {
    Write-Host "${Green}[SUCCESS]${Reset} $message"
}

function Write-Warning($message) {
    Write-Host "${Yellow}[WARNING]${Reset} $message"
}

function Write-Error($message) {
    Write-Host "${Red}[ERROR]${Reset} $message"
}

# Check if running on Windows
if (-not $IsWindows -and -not ($env:OS -match "Windows")) {
    Write-Error "This script is designed for Windows. Use the shell script for Linux/Mac."
    exit 1
}

# Get the project root directory
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptPath

Write-Status "Kribble Mobile Testing Tunnel"
Write-Status "Project Root: $projectRoot"
Write-Status "Backend Port: $BackendPort"
Write-Status "Frontend Port: $FrontendPort"
Write-Status "Provider: $Provider"
Write-Host ""

# Function to check if a command exists
function Test-Command($command) {
    $null = Get-Command $command -ErrorAction SilentlyContinue
    return $?
}

# Function to get local IP address
function Get-LocalIP {
    $ip = (Get-NetIPAddress -AddressFamily IPv4 | 
           Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |
           Select-Object -First 1).IPAddress
    return $ip
}

# Function to update environment file
function Update-EnvFile($tunnelUrl) {
    $envFile = Join-Path $projectRoot "client/.env.development.local"
    
    $content = @"
# Auto-generated by mobile-tunnel.ps1
# Created at: $(Get-Date)
VITE_API_URL=$tunnelUrl
VITE_SOCKET_URL=$tunnelUrl
"@
    
    $content | Out-File -FilePath $envFile -Encoding UTF8
    Write-Success "Updated $envFile with tunnel URL: $tunnelUrl"
}

# Function to check if servers are running
function Test-Server($port, $name) {
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:$port/api/health" -TimeoutSec 2 -ErrorAction SilentlyContinue
        if ($response.StatusCode -eq 200) {
            return $true
        }
    } catch {
        # Try just the port
        try {
            $client = New-Object System.Net.Sockets.TcpClient
            $client.Connect("localhost", $port)
            $client.Close()
            return $true
        } catch {
            return $false
        }
    }
    return $false
}

# Main script logic
Write-Status "Checking prerequisites..."

# Check if servers are running
$backendRunning = Test-Server $BackendPort "Backend"
$frontendRunning = Test-Server $FrontendPort "Frontend"

if (-not $backendRunning) {
    Write-Warning "Backend server not detected on port $BackendPort"
    Write-Status "Start it with: cd server && npm run dev"
    $startBackend = Read-Host "Would you like to start the backend server now? (y/n)"
    if ($startBackend -eq "y") {
        Write-Status "Starting backend server..."
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd '$projectRoot/server'; npm run dev" -WindowStyle Normal
        Write-Status "Waiting for backend to start..."
        Start-Sleep -Seconds 5
        
        # Retry check
        $backendRunning = Test-Server $BackendPort "Backend"
        if (-not $backendRunning) {
            Write-Warning "Backend still not responding. Please check manually."
        }
    }
}

if (-not $frontendRunning) {
    Write-Warning "Frontend server not detected on port $FrontendPort"
    Write-Status "Start it with: cd client && npm run dev"
}

Write-Host ""

# Provider-specific setup
switch ($Provider) {
    "ngrok" {
        Write-Status "Setting up ngrok tunnel..."
        
        if (-not (Test-Command "ngrok")) {
            Write-Error "ngrok not found. Please install it first:"
            Write-Status "  choco install ngrok"
            Write-Status "  OR download from https://ngrok.com/download"
            exit 1
        }
        
        # Check if authtoken is configured
        $ngrokConfig = "$env:USERPROFILE\.ngrok2\ngrok.yml"
        if (-not (Test-Path $ngrokConfig)) {
            Write-Warning "ngrok authtoken not configured"
            Write-Status "Get your token from: https://dashboard.ngrok.com/get-started/your-authtoken"
            $token = Read-Host "Enter your ngrok authtoken"
            if ($token) {
                ngrok config add-authtoken $token
            } else {
                Write-Error "Authtoken required"
                exit 1
            }
        }
        
        # Build ngrok command
        $ngrokArgs = "http $BackendPort"
        if ($StaticDomain -and $Domain) {
            $ngrokArgs = "http --domain=$Domain $BackendPort"
        }
        
        Write-Status "Starting ngrok tunnel..."
        Write-Status "Command: ngrok $ngrokArgs"
        Write-Host ""
        Write-Warning "Once ngrok starts, copy the HTTPS URL and press Enter"
        Write-Host ""
        
        # Start ngrok in new window
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "ngrok $ngrokArgs" -WindowStyle Normal
        
        # Wait for user to copy URL
        $tunnelUrl = Read-Host "Paste the ngrok HTTPS URL here (e.g., https://xxxx.ngrok.io)"
        
        if ($tunnelUrl -match "^https://") {
            Update-EnvFile $tunnelUrl
            
            Write-Host ""
            Write-Success "Setup complete!"
            Write-Status "Tunnel URL: $tunnelUrl"
            Write-Status "Updated client/.env.development.local"
            Write-Host ""
            Write-Status "Next steps:"
            Write-Host "  1. Restart your frontend dev server (if running)"
            Write-Host "  2. Access from mobile using:"
            Write-Host "     - Local IP: http://$(Get-LocalIP):$FrontendPort"
            Write-Host "     - Or the ngrok URL for API testing"
            Write-Host ""
            Write-Status "To stop: Close the ngrok window"
        } else {
            Write-Error "Invalid URL format. Expected: https://xxxx.ngrok.io"
        }
    }
    
    "cloudflare" {
        Write-Status "Setting up Cloudflare Tunnel..."
        
        if (-not (Test-Command "cloudflared")) {
            Write-Error "cloudflared not found. Please install it:"
            Write-Status "  Download from: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
            exit 1
        }
        
        Write-Status "Checking tunnel status..."
        
        # List existing tunnels
        $tunnels = cloudflared tunnel list 2>$null
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "Not authenticated with Cloudflare"
            Write-Status "Run: cloudflared tunnel login"
            Write-Status "Then re-run this script"
            exit 1
        }
        
        Write-Host ""
        Write-Status "Available tunnels:"
        cloudflared tunnel list
        
        Write-Host ""
        $tunnelName = Read-Host "Enter tunnel name (or 'new' to create one)"
        
        if ($tunnelName -eq "new") {
            $newName = Read-Host "Enter new tunnel name (e.g., kribble-dev)"
            cloudflared tunnel create $newName
            $tunnelName = $newName
        }
        
        Write-Status "Starting tunnel: $tunnelName"
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "cloudflared tunnel run $tunnelName" -WindowStyle Normal
        
        Write-Success "Cloudflare tunnel started!"
        Write-Status "Your backend is now accessible via your permanent domain"
    }
    
    "localtunnel" {
        Write-Status "Setting up LocalTunnel..."
        
        # Check if npx is available
        if (-not (Test-Command "npx")) {
            Write-Error "npx not found. Please install Node.js"
            exit 1
        }
        
        Write-Status "Starting localtunnel..."
        Write-Warning "LocalTunnel provides random URLs that change each time"
        Write-Host ""
        
        # Start localtunnel in new window
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "npx localtunnel --port $BackendPort" -WindowStyle Normal
        
        Write-Warning "Once LocalTunnel starts, copy the URL and press Enter"
        $tunnelUrl = Read-Host "Paste the LocalTunnel URL here"
        
        if ($tunnelUrl -match "^https?://") {
            Update-EnvFile $tunnelUrl
            Write-Success "Setup complete with URL: $tunnelUrl"
        }
    }
}

Write-Host ""
Write-Status "Local IP for direct WiFi access: $(Get-LocalIP)"
Write-Status "Make sure your phone is on the same WiFi network!"
